FROM nvidia/cuda:8.0-cudnn6-runtime-ubuntu16.04

RUN apt-get update && apt-get install -y --no-install-recommends gcc python-pip python-dev
RUN pip install -U pip
RUN pip install -U setuptools
RUN pip install -U ipython
RUN pip install -U virtualenv
