FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    ccache \
    clang-format-3.8 \
    cmake \
    curl \
    g++ \
    git \
    libhdf5-dev \
    libtool \
    make \
    python3-dev \
    python3-pip \
    python3-setuptools \
    unzip \
    wget \
    zip \
    zlib1g-dev

RUN curl -L https://github.com/google/protobuf/archive/v3.1.0.tar.gz -o /tmp/protobuf-v3.1.0.tar.gz \
    && cd /tmp \
    && apt-get install -y autoconf automake \
    && tar xvf protobuf-v3.1.0.tar.gz \
    && cd protobuf-3.1.0 \
    && ./autogen.sh \
    && ./configure --disable-shared\
    && make \
    && make install \
    && ldconfig \
    && chmod -R a+r /usr/local \
    && find /usr/local -type d |xargs chmod a+x

ADD python/requirements.txt /tmp/deps/
RUN pip3 install -U pip
RUN pip3 install -U wheel
RUN pip3 install -U -r /tmp/deps/requirements.txt
